"""
DSL Query Processor

Simple processor that generates Elasticsearch DSL queries from natural language
using OpenAI Agent SDK, similar to the test.py approach.
"""
import logging
import os
import json
import pandas as pd
from agents import Agent, Runner, ModelSettings
from openai.types import Reasoning
from typing import Dict, Any
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class DSLQuery(BaseModel):
    """Elasticsearch DSL query payload"""
    query: Dict[str, Any] = Field(..., description="Elasticsearch DSL query payload")


class SimpleDSLProcessor:
    """
    Simple processor that generates Elasticsearch DSL queries from natural language.
    Based on the test.py approach with CSV schema and DSL rules.
    """
    
    def __init__(self):
        self.api_key = os.getenv('OPENAI_API_KEY')
        if not self.api_key:
            raise ValueError("OPENAI_API_KEY environment variable not set")
        
        self.model = "o3"
        self.reasoning_effort = Reasoning(effort="medium")
        
        self._load_schema_and_rules()
        
        self.system_instructions = self._build_system_instructions()

        logger.info(f"SimpleDSLProcessor initialized with {self.model} model and schema-based DSL generation")

    def _load_schema_and_rules(self):
        """Load CSV schema and DSL rules like test.py"""
        config_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'config')
        csv_path = os.path.join(config_dir, 'coresignal_fields.csv')
        try:
            df = pd.read_csv(csv_path)
            self.schema_context = df.to_dict(orient="records")
            logger.info(f"Loaded schema with {len(self.schema_context)} fields")
        except Exception as e:
            logger.error(f"Error loading CSV schema: {e}")
            raise
        rules_path = os.path.join(config_dir, 'query_dsl_rules.txt')
        try:
            with open(rules_path, 'r', encoding='utf-8') as f:
                self.query_dsl_instructions = f.read().strip()
            logger.info("Loaded DSL rules")
        except Exception as e:
            logger.error(f"Error loading DSL rules: {e}")
            raise

    def _build_system_instructions(self):
        """Build system instructions"""
        return f"""
You are an assistant that generates Elasticsearch DSL query payloads from user prompts. User prompts may contain extra information that is not relevant to the query, so you must focus on extracting only the necessary fields.

You must use the schema provided below. Each entry contains:
-Parameters: The exact Elasticsearch field name to be used in the query.
-Priority: Indicates how important the field is when generating filters.
-How LLM can fill this data: Describes how to infer the value from a user prompt.
-Example Identifier to Search: A sample phrase in the prompt that suggests this field is relevant.
-Example Query Parameter Generated by LLM: A sample value the LLM should generate for the query.
-Type: The Elasticsearch data type that determines which query operator to use.
Schema:
{json.dumps(self.schema_context, indent=2)}
You must generate a valid Elasticsearch DSL query payload that should adhere to the rules below:

{self.query_dsl_instructions}

For each parameter in the schema, The type should be strictly followed.
Also the results should exclude any company from education industry
IMPORTANT: Follow section 12 "Output Format Rules" exactly:
- Must be a single valid JSON object
- Must contain only the top-level "query" key  
- Must use correct syntax and nesting
- Must not include pagination
- Must not include any extra keys or wrappers
- Also instead of using match_phrase, use match for text fields
- Do not use iso codes, only stick to region/country/city unless directly specified in the prompt
"""

    async def process_query(self, user_query: str) -> Dict[str, Any]:
        """
        Generate DSL query from natural language (like test.py approach).
        
        Args:
            user_query: Natural language search query
            
        Returns:
            Dictionary with generated DSL query and metadata
        """
        try:
            logger.info(f"Processing query: {user_query}")
            agent = Agent(
                name="ElasticsearchQueryAgent",
                model=self.model,
                model_settings=ModelSettings(
                    reasoning=self.reasoning_effort,
                    extra_body={"service_tier": "flex"}
                ),
                instructions=self.system_instructions
            )
            
            result = await Runner.run(
                starting_agent=agent,
                input=user_query
            )
            
            total_tokens = 0
            if hasattr(result, 'usage_summary') and result.usage_summary:
                input_tokens = getattr(result.usage_summary, 'input_tokens', 0)
                output_tokens = getattr(result.usage_summary, 'output_tokens', 0)
                total_tokens = input_tokens + output_tokens
            
            dsl_query_result = result.final_output
            logger.info(f"Raw agent output: {dsl_query_result}")
            print("Raw agent output:", dsl_query_result)
            return dsl_query_result
           

        except Exception as e:
            logger.error(f"Query processing failed: {str(e)}")
            raise Exception(f"DSL generation failed: {str(e)}") 