// API exports
export { baseApi, AUTH_TOKEN_KEY } from './baseApi';

// Auth API
export {
  authApi,
  useLoginMutation,
  useRegisterMutation,
  useGetMeQuery,
  useLazyGetMeQuery,
  useLogoutMutation,
  useLogoutAllMutation,
  getStoredToken,
  getStoredUser,
  isAuthenticated,
  clearAuthData,
} from './authApi';
export type {
  User,
  AuthData,
  AuthResponse,
  MeResponse,
  LogoutResponse,
  LoginRequest,
  RegisterRequest,
} from './authApi';
export { 
  campaignApi, 
  useGetCampaignsQuery,
  useGetProspectingCampaignsQuery,
  useCreateCampaignMutation,
  useCheckCampaignNameMutation,
  useCreateCampaignFromProspectingJobMutation,
  useCreateCampaignFromSingleCompanyMutation,
  useCreateCampaignFromCSVImportMutation,
  useCreateCampaignFromSimilarSearchMutation,
  useGetCampaignDetailsQuery,
  useLazyGetCampaignDetailsQuery,
  useManualCompanyQualificationMutation,
  useGetApolloContactListMutation,
  useEnrichApolloContactListMutation,
  useUpdateApolloContactEnrichmentStatusMutation,
  useAiCompanyQualificationMutation,
  useCompanyQualificationProgressQuery,
  useLazyCompanyQualificationProgressQuery,
  useAiContactQualificationMutation,
  useContactQualificationProgressQuery,
  useLazyContactQualificationProgressQuery,
  useGetCampaignContactListQuery,
  useLazyGetCampaignContactListQuery,
  // Optimized APIs
  useGetContactListMinimalQuery,
  useLazyGetContactListMinimalQuery,
  useGetCampaignStatusMinimalQuery,
  useLazyGetCampaignStatusMinimalQuery,
  useGetCompanyListMinimalQuery,
  useLazyGetCompanyListMinimalQuery,
  useGetHubspotSyncCandidatesQuery,
  useLazyGetHubspotSyncCandidatesQuery,
  useSyncToHubspotMutation,
  useLazyGetHubspotSyncProgressQuery,
  useGeneratePersonalizationMutation,
  useLazyGetPersonalizationResultsQuery,
  useSaveContactPersonalizationMutation,
  useBulkSaveContactPersonalizationMutation,
  useGetEnrollmentContactsQuery,
  useLazyGetEnrollmentContactsQuery,
  useEnrollContactsToSequenceMutation,
  useGetLemlistCampaignsQuery,
  // Export Contacts APIs
  useGetExportContactsMetadataQuery,
  useLazyGetExportContactsMetadataQuery,
} from './campaignApi';
export type { 
  Campaign, 
  CampaignsResponse, 
  GetCampaignsParams,
  GetProspectingCampaignsParams,
  CreateCampaignPayload,
  CreateCampaignResponse,
  CreateCampaignFromProspectingJobPayload,
  CreateCampaignFromProspectingJobResponse,
  CreateCampaignFromSingleCompanyPayload,
  CreateCampaignFromSingleCompanyResponse,
  CreateCampaignFromCSVImportPayload,
  CreateCampaignFromCSVImportResponse,
  ManualCompanyQualificationPayload,
  ManualCompanyQualificationResponse,
  GetApolloContactListParams,
  GetApolloContactListResponse,
  UpdateApolloContactEnrichmentStatusParams,
  UpdateApolloContactEnrichmentStatusResponse,
  AiCompanyQualificationPayload,
  AiCompanyQualificationResponse,
  AiContactQualificationPayload,
  AiContactQualificationResponse,
  ContactQualificationProgressData,
  ContactQualificationProgressResponse,
  CompanyQualificationProgressData,
  CompanyQualificationProgressResponse,
  HubspotSyncCandidate,
  GetHubspotSyncCandidatesParams,
  GetHubspotSyncCandidatesResponse,
  CampaignContactListItem,
  GetCampaignContactListParams,
  GetCampaignContactListResponse,
  // Optimized API types
  ContactMinimal,
  GetContactListMinimalParams,
  GetContactListMinimalResponse,
  GetCampaignStatusMinimalParams,
  GetCampaignStatusMinimalResponse,
  CompanyMinimal,
  GetCompanyListMinimalParams,
  GetCompanyListMinimalResponse,
  CampaignCompany,
  CampaignDetailsResponse,
  GetCampaignDetailsParams,
  // Export Contacts API types
  ExportContactsMetadataResponse,
  GetExportContactsMetadataParams,
} from './campaignApi';
export { 
  companyApi, 
  useGetCompaniesQuery,
  useLazyGetCompaniesQuery,
  useGetCompanyDetailsQuery,
  useLazyGetCompanyDetailsQuery,
} from './companyApi';
export type { 
  Company, 
  Contact, 
  CompaniesResponse, 
  CompanyDetailsResponse,
  GetCompaniesParams,
  GetCompanyDetailsParams,
  Pagination,
} from './companyApi';

// Meetings API
export {
  meetingsApi,
  useCreateMeetingMutation,
  useGetMeetingsQuery,
  useGetCompletedMeetingsQuery,
  useGetMeetingsByCompanyQuery,
  useGetMeetingQuery,
  useGetMeetingByUuidQuery,
  useUpdateMeetingMutation,
  useDeleteMeetingMutation,
  useStartMeetingMutation,
  useGenerateBattlecardMutation,
  useGetBattlecardQuery,
  useGenerateReflectionsMutation,
  useGetReflectionsQuery,
  useUpdateManualReflectionsMutation,
} from './meetingsApi';
export type {
  Meeting,
  TranscriptEntry,
  LiveInsight,
  ActionItem,
  Battlecard,
  AIReflections,
  ManualReflections,
  MeetingReflections,
  CreateMeetingRequest,
  UpdateMeetingRequest,
  UpdateManualReflectionsRequest,
  GetMeetingsParams,
} from './meetingsApi';
