// API exports
export { baseApi } from './baseApi';
export { 
  campaignApi, 
  useGetCampaignsQuery,
  useGetProspectingCampaignsQuery,
  useCreateCampaignMutation,
  useCreateCampaignFromProspectingJobMutation,
  useCreateCampaignFromSingleCompanyMutation,
  useCreateCampaignFromCSVImportMutation,
  useGetCampaignDetailsQuery,
  useLazyGetCampaignDetailsQuery,
  useManualCompanyQualificationMutation,
  useGetApolloContactListMutation,
  useEnrichApolloContactListMutation,
  useUpdateApolloContactEnrichmentStatusMutation,
  useAiCompanyQualificationMutation,
  useCompanyQualificationProgressQuery,
  useGetCampaignContactListQuery,
  useLazyGetCampaignContactListQuery,
  useGetHubspotSyncCandidatesQuery,
  useLazyGetHubspotSyncCandidatesQuery,
  useSyncToHubspotMutation,
  useLazyGetHubspotSyncProgressQuery,
  useGeneratePersonalizationMutation,
  useLazyGetPersonalizationResultsQuery,
  useSaveContactPersonalizationMutation,
  useBulkSaveContactPersonalizationMutation,
  useGetEnrollmentContactsQuery,
  useLazyGetEnrollmentContactsQuery,
  useEnrollContactsToSequenceMutation,
} from './campaignApi';
export type { 
  Campaign, 
  CampaignsResponse, 
  GetCampaignsParams,
  GetProspectingCampaignsParams,
  CreateCampaignPayload,
  CreateCampaignResponse,
  CreateCampaignFromProspectingJobPayload,
  CreateCampaignFromProspectingJobResponse,
  CreateCampaignFromSingleCompanyPayload,
  CreateCampaignFromSingleCompanyResponse,
  CreateCampaignFromCSVImportPayload,
  CreateCampaignFromCSVImportResponse,
  ManualCompanyQualificationPayload,
  ManualCompanyQualificationResponse,
  GetApolloContactListParams,
  GetApolloContactListResponse,
  UpdateApolloContactEnrichmentStatusParams,
  UpdateApolloContactEnrichmentStatusResponse,
  AiCompanyQualificationPayload,
  AiCompanyQualificationResponse,
  CompanyQualificationProgressData,
  CompanyQualificationProgressResponse,
  HubspotSyncCandidate,
  GetHubspotSyncCandidatesParams,
  GetHubspotSyncCandidatesResponse,
  CampaignContactListItem,
  GetCampaignContactListParams,
  GetCampaignContactListResponse,
  CampaignCompany,
  CampaignDetailsResponse,
  GetCampaignDetailsParams,
} from './campaignApi';
export { 
  companyApi, 
  useGetCompaniesQuery, 
  useGetCompanyDetailsQuery,
  useLazyGetCompanyDetailsQuery,
} from './companyApi';
export type { 
  Company, 
  Contact, 
  CompaniesResponse, 
  CompanyDetailsResponse,
  GetCompaniesParams,
  GetCompanyDetailsParams,
  Pagination,
} from './companyApi';

